## PROG8245 Assignment 1: (Total Marks 100)
## Start on 16th of September- Due on 27th of September

- TODO: write your name and ID below
- Name: Syed Muzammil Syed Riyaz Ahamed
- ID: 9012161
- Kindly note that this assignment is to be solved by yourself, without the use of AI and chatbots.
- If chatbot usage is detected, the penalty that is discussed in Week 1 slides will apply.
- Each code block will have a Todo comment which explains the functionality, expected input, and expected output of the function.
- There are 10 marks in this assignment for assuring that the code couldn't be broken (no errors can be thrown, please consider mathematical and logical errors)
- There are 10 marks in this assignment for commenting and code readability.


### Part 1: Python Basics

#### Question 1:

In [6]:
def total_price(price, tax):
    # 3 marks
    # TODO: write the functionality of the code where
    #  you are taking as an input a price of an item and the
    #  tax in decimal (13% tax will be given as 0.13),
    #  you should return the taxedPrice of that item
    #  which will be the total price after tax a customer must pay
    # (The price of the item plus the applicable taxes)

    # Calculating the taxed amount
    tax_amount = price * tax
    price_after_tax = price + tax_amount
    
    return price_after_tax

# Method calling, assigning values and displaying the output
x = 10
price = 70
tax = 0.13
final_price = total_price(price, tax)
print("The final amount after tax:", final_price)


The final amount after tax: 79.1


#### Question 2:

In [7]:
def divisible_by(x, y):
    # 3 marks
    # TODO: write a function that returns True if x is divisible by y,
    #  and returns False OTHERWISE (all other cases).

    # Checking the divisibility
    if x % y == 0:
        return True

    return False

# Method calling, assigning values and displaying the output
x = 10
x = 10
y = 2
print(divisible_by(x,y))

True


#### Question 3:

In [8]:
def basic_calculator(x, y, operator):
    # 5 marks
    # TODO: write the functionality of the code where you are
    #  coding a basic calculator that performs basic addition "+", subtraction "-",
    #  multiplication "*", division "/", modulus "%" and integer division "//"
    #  the function must apply the operator to x and y for example:
    #  basicCalculator(10, 15, "*") should apply 10*15 and save it to the result variable
    #  NOTE: YOU NEED TO HANDLE DIVISION ERRORS BY RETURNING A STRING WITH THE WORD "error"
    #  NOTE: YOU NEED TO HANDLE AN INVALID OPERATOR BY RETURNING A STRING HAVING THE WORD "invalid"

     # Conditions for basic calculator

     # Addition
     if operator == "+":
          result = x + y
     
     # Subtraction
     elif operator == "-":
          result = x - y 

     # Multiplication
     elif operator == "*":
          result = x*y 

     # Division
     elif operator == "/":
          if y != 0:
               result = x/y 
          else:
               result = print("\nCannot divide by zero")

     # Modulus
     elif operator == "%":
          if y != 0:
               result = x%y
          else:
               result = print("\nCannot divide by zero")

     # Integer Division
     elif operator == "//":
          if y != 0:
               result = x//y
          else:
               result = print("\nCannot divide by zero")
     else:
          return("\nInvalid Operand")
          
     return result


# Method calling, assigning values and displaying the output
x = 10
y = 2
addition = basic_calculator(x, y, "+")
print(f"The addition value of x an y is {addition}")

subtract = basic_calculator(x, y, "-")
print(f"\nThe subtraction value of x an y is {subtract}")

multiply = basic_calculator(x, y, "*")
print(f"\nThe multiplication value of x an y is {multiply}")

divide = basic_calculator(x, y, "/")

modulus = basic_calculator(x, y, "%")

int_divide = basic_calculator(x, y, "//")


if y != 0:
     print(f"\nThe division value of x an y is {divide}")
     print(f"\nThe modulus value of x an y is {modulus}")
     print(f"\nThe integer division value of x an y is {int_divide}")

   

The addition value of x an y is 12

The subtraction value of x an y is 8

The multiplication value of x an y is 20

The division value of x an y is 5.0

The modulus value of x an y is 0

The integer division value of x an y is 5


#### Question 4:

In [9]:
def sum_of_even(numbers_list):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a list of numbers
    # returning the sum of even numbers in the list
    # NOTE: YOU NEED TO HANDLE ERRORS OF GIVING LIST OF STRINGS OR/AND
    #  STRINGS WITH NUMBERS by returning "invalid"
    # sum_of_even([1,2,3,4,5,6]) = 12

    result = 0
    for number in numbers_list:
        if number % 2 == 0:
            result += number
    return result

# Method calling, assigning values and displaying the output
x = 10
num_list = ([1,2,3,4,5,6,7,8,9,10])

print("The sum of of even numbers are:", sum_of_even(num_list))

The sum of of even numbers are: 30


#### Question 5:

In [10]:
def reverse_string(input_string):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a string
    # returns the reverse of the string
    # reverse_string("hello") = "olleh"
    # NOTE: Numbers should be handled as strings ex: 123 returns "321"

    input_string = str(input_string)
    reversed_string = ""

    # Performing reverse string operation
    for char in input_string:
        reversed_string = char + reversed_string
    return reversed_string

# Method calling, assigning values and displaying the output
string_value = "Hello World"
integer_value = 12345
print("The reversed value is:", reverse_string(string_value))
print("The reversed value is:", reverse_string(integer_value))

The reversed value is: dlroW olleH
The reversed value is: 54321


#### Question 6:

In [11]:
def diamond_string(length):
    # 5 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a POSITIVE ODD length
    # saves in a string the diamond as follows:
    # diamond_string(5)
    #   *
    #  ***
    # *****
    #  ***
    #   *
    # NOTE: The input must be positive odd, if not return empty string ""   

    # Check for odd numbers
    if length <= 0 | length % 2 == 0:
        return ""
    
    diamond = []

    # Upper half
    for i in range(length//2 + 1):
        spaces = ' ' * (length//2 - i)
        stars = '*' * (2 * i + 1)
        diamond.append(spaces + stars)

    # Lower half
    for i in range(length//2 - 1, -1, -1):
        spaces = ' ' * (length//2 - i)
        stars = '*' * (2 * i + 1)
        diamond.append(spaces + stars)
    
    return '\n' .join(diamond)

# Method calling, assigning values and displaying the output
length = 5
diamond = diamond_string(length)
print(diamond)


  *
 ***
*****
 ***
  *


#### Question 7:

In [12]:
def longest_consecutive_subarray(number_array):
    # 8 marks
    # TODO: write the functionality of the code where you are
    # taking as an input an array of REAL NUMBERS
    # return the length of the longest subarray that could be
    # built using the input
    # longest_consecutive_subarray([100, 4, 200, 1, 3, 2]) = 4
    # Function should return 4 which represents in this case
    # the longest_consecutive_subarray that could be built [1,2,3,4]
    # You can't use Built in Sorting!
    # Note: - If any error exists in the input, "error" should be returned
    #       - The difference between any 2 consecuetive numbers is 1.

    # Checking the input type and datatype
    if isinstance(number_array, list) != True | all(isinstance(x, (int, float)) for x in number_array) != True:
        return "error"
    
    for num in number_array:

        # Checking if it's the start of a sequence
        if num - 1 not in number_array:
            current_num = num
            current_streak = 1
            
            # Incrementing and checking for consecutive numbers
            while current_num + 1 in number_array:
                current_num += 1
                current_streak += 1
    
    return current_streak

num_array = [100, 4, 200, 1, 3, 2]
longest_array = longest_consecutive_subarray(num_array) 
print(f"The longest consecutive subarray is {longest_array}") 

The longest consecutive subarray is 4


#### Question 8 (Challenging):

In [13]:
def can_be_segmented(input_string, word_dict):
    # 15 marks
    # TODO: Write the functionality of the code where you
    # are given as an input a string and a word_dict
    # Your target is to return True, if input_string can be segmented
    # (broken-down) into a sequence of one or more dictionary words
    # otherwise return False
    # Sample Input: can_be_segmented("applepenapple", {'apple','pen'}) ==> True
    # Sample Input: can_be_segmented("catsandog", {'cats','dog','sand','and','cat'}) ==> False
    # Hint: You can start by checking which prefix exist in the dictionary, and call the same function recursively
    # on the remaining string.
    
    # Checks the string character by character
    if input_string == '':
        return True
        
    # Segmentation process
    for i in range(1, len(input_string) + 1):
        prefix = input_string[:i]
        if prefix in word_dict:
            if can_be_segmented(input_string[i:], word_dict):
                return True
                    
            return False

# Method calling, assigning values and displaying the output
print(can_be_segmented("applepenapple", {'apple','pen'}))
print(can_be_segmented("catsandog", {'cats','an','dog','and','cat'}))

True
False


### Part 2: Numpy Basics: 
- In this Part of the assignment, you are <b>ONLY ALLOWED</b> to use Numpy and its functions. 
- You are not expected to use Loops.

In [14]:
import numpy as np

#### Question 9:

In [15]:
def no_zeros(array_input):
    # 3 marks
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: np.array([1,2,3,4,5,6,0]) Sample Output: False
    ## Sample input: np.array([1,2,3,4,5,6]) Sample Output: True

    # Checking the array if it contains zero
    nonZeroValues = np.all(array_input)
    return nonZeroValues

# Method calling, assigning values and displaying the output
array1 = np.array([1,2,3,4,5,6,0])
array2 = np.array([1,2,3,4,5,6])
print(no_zeros(array1))
print(no_zeros(array2))


False
True


#### Question 10:

In [16]:
def two_dimensions(n):
    # 7 marks
    ## TODO: This function should create a 2d Array of shape n*n for any positive number
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]

    array = np.zeros((n, n), dtype = int)

    # Sets 1 for the top row
    array[0,:] = 1

    # Sets 1 for Bottom row
    array[2,:] = 1

    # Sets 1 for Right column
    array[:,2] = 1

    # Sets 1 for Left column
    array[:,0] = 1
    
    return array

# Method calling, assigning values and displaying the output
n = 3
print(two_dimensions(n))

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### Question 11:

In [17]:
def random_generation(n,min,max):
    # 5 marks
    # TODO: Write a function that takes as an input
    # Dimension of 2d Array n, min and max
    # Generate an n*n array with random numbers between
    # min and max inclusive
    # Such that no element is duplicated
    # return numpy array
    # Implement this function using ONLY numpy methods
    # Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]

    # Total number of elements
    total_elements = n * n

    # Assigning random numbers for the number of elements with the given min and max values
    random_number = np.random.permutation(np.arange(min, max + 1))[:total_elements]

    return random_number.reshape(n, n)

# Method calling, assigning values and displaying the output
n = 3
min_value = 0
max_value = 12
print("Randomly generated values:\n")
print(random_generation(n, min_value, max_value))

Randomly generated values:

[[10  3  8]
 [ 9  4  5]
 [ 0 11 12]]


#### Question 12:

In [18]:
def matrix_border_sum(matrix):
    # 8 marks
    # TODO: Write a function that takes as an input a matrix
    # and return the sum of all elements in the borders
    # Implement this function using ONLY numpy methods
    # Sample Input: np.array([[1,2,3],
    #                         [4,5,6],
    #                         [7,8,9]])
    # Output: matrix_border_sum(matrix) =  1+2+3+4+6+7+8+9 = 40

    # Takes the entire Row 0
    top_row = matrix[0, :]

    # Takes the entire Row 2
    bottom_row = matrix[2, :]

    # Takes Column 0 by excluding thw values in Row 0 and 1
    left_column = matrix[1:2, 0]

    # Takes Column 1 by excluding thw values in Row 0 and 1
    right_column = matrix[1:2, 2]

    # Summation of the border matrix values
    sum_matrix = np.sum(top_row) + np.sum(bottom_row) + np.sum(left_column) + np.sum(right_column)
    return sum_matrix

# Method calling, assigning values and displaying the output
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum = matrix_border_sum(matrix)
print(f"The sum of border values in the give matrix is {sum}")

The sum of border values in the give matrix is 40


### Part 3: Pandas

In [19]:
import pandas as pd

#### Question 13 (12 marks): 
- Using RegularSeasonCompactResults.csv and Teams.csv apply the following functionalities

In [20]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter to show if there are any draw matches
# 2- Apply the filter to the dataframe
# 3- SHOW/PRINT the dataframe length or count (4 marks)
## TODO: Your code should be here

class Results:

    def results():

        # Reading the csv file
        df = pd.read_csv('D:\Machine Learning Programming\Assignments\Assignment 1\RegularSeasonCompactResults.csv')

        # Displaying the data
        print("Data in the RegularSeasonCompactResults file is displayed below:\n")
        print(df.head())

        # Checking for draw matches
        draw_matches = df[df['Wscore'] == df['Lscore']]

        draw_matches_count = len(draw_matches)

        print (f"\nThe number of matches that are turned out to be draw is {draw_matches_count}")

# Creating object for a class, Method calling and displaying the output
result = Results
result.results()

Data in the RegularSeasonCompactResults file is displayed below:

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

The number of matches that are turned out to be draw is 0


In [21]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter showing the entries where the winningteamID= 1400- (last two digits of your id)
# 2- Create another filter for the season of 2013
# 3- Apply the filter to the dataframe
# 4- Show the resulted dataframe (4 marks)
# (Example: IF your id is 8000021, the winning team id = 1400-21= 1379)
# TODO: Your code should be here

class Season:
    
    def seasons():

        # Reading the csv file
        df = pd.read_csv('D:\Machine Learning Programming\Assignments\Assignment 1\RegularSeasonCompactResults.csv')
        winning_team_id = 1400 - 61

        # Apply the filters for the winning team and the season of 2013
        filtered_df = df[(df['Wteam'] == winning_team_id) & (df['Season'] == 2013)]

        return filtered_df

# Creating object for a class, Method calling and displaying the output
season = Season
print("The winning team and its seasons are displayed below:\n")
print(season.seasons())


The winning team and its seasons are displayed below:

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
124186    2013      10   1339      51   1226      48    H      0
124518    2013      16   1339      81   1340      60    H      0
125428    2013      42   1339      69   1167      51    H      0
125513    2013      44   1339      74   1316      64    H      0
125713    2013      48   1339      57   1133      55    N      0
126438    2013      68   1339      68   1258      64    A      0
127598    2013      94   1339      69   1258      60    H      0
127925    2013     101   1339      78   1362      76    A      0
128246    2013     108   1339      70   1360      67    H      0


In [22]:
# Using RegularSeasonCompactResults.csv & Teams.csv
# 1- Load and merge both dataframes
# 2- Where the merge is on WinningTeamId (RegularSeasonCompactResults) and TeamId (Teams.csv)
# 3- Name the dataframe: DFCombined
# 4- Show the top 3 rows (4 marks)
# TODO: Your code should be here

class Merge_DF:

    def dataframe_merge():

        # Reading the csv files
        season_df = pd.read_csv('D:\Machine Learning Programming\Assignments\Assignment 1\RegularSeasonCompactResults.csv')
        teams_df = pd.read_csv('D:\Machine Learning Programming\Assignments\Assignment 1\Teams.csv')

        # Displaying the data
        print(f"The dataframe of the RegularSeasonCompactResults is displayed below:\n\n{season_df.head()}")
        print(f"\nThe dataframe of the Teams is displayed below:\n\n{teams_df.head()}")

        # Taking the winning team id based on my Id number
        winning_team_id = season_df[season_df['Wteam'] == 1339]
        
        # Combining the dataframe
        DFCombined = pd.merge(winning_team_id, teams_df, left_on='Wteam', right_on='Team_Id')

        print(f"\nThe combined dataframe of RegularSeasonCompactResults and Teams is displayed below:\n\n{DFCombined.head(3)}")

# Creating object for a class, Method calling and displaying the output
merge_df = Merge_DF
merge_df.dataframe_merge()

The dataframe of the RegularSeasonCompactResults is displayed below:

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

The dataframe of the Teams is displayed below:

   Team_Id    Team_Name
0     1101  Abilene Chr
1     1102    Air Force
2     1103        Akron
3     1104      Alabama
4     1105  Alabama A&M

The combined dataframe of RegularSeasonCompactResults and Teams is displayed below:

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Team_Id Team_Name
0    1985      26   1339      73   1334      61    H      0     1339  Portland
1    1985      29   1339      82   1363      81    A      0     1339  Portland
2    1985      32   1339      46   1186      44    H  